---
language: python

env:
  - IMAGE=ubuntu TAG=bionic

dist: bionic

cache: pip

before_install:
  - docker version
  - docker pull $IMAGE:$TAG
  - docker run --name test -di $IMAGE:$TAG /bin/sh
  - docker exec test apt-get update
  - docker exec test apt-get install -y python ca-certificates

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg
  - pip install ansible-lint
  - ansible-lint --version

before_script:
  - ansible-galaxy install uchida.nvidia-repo

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - travis_wait ansible-playbook -i test, --diff tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
